version: '3'

services:
  app:
    image: 0xb1b1/vaultwarden-server:latest
    container_name: vaultwarden-app
    volumes:
      - ./data:/data
    ports:
      - 23406:80
    restart: unless-stopped
