version: '3'

services:
  proxy:
    image: 0xb1b1/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 23400:80
      - 23401:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: nextcloud-postgres
    networks:
      - nextcloud_network
    volumes:
      - ./database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=pgrandompassword
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - ./app:/var/www/html
      - /mnt/your-drive/docker/mounts/nextcloud/app/config:/var/www/html/config
      - /mnt/your-drive/docker/mounts/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /mnt/your-drive/docker/mounts/nextcloud/app/data:/var/www/html/data
      - /mnt/your-drive/docker/mounts/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=fqdn.example
      - LETSENCRYPT_HOST=fqdn.example
      - LETSENCRYPT_EMAIL=email@example.example
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=pgrandompassword
    restart: unless-stopped

networks:
  nextcloud_network:
